// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcfxamobzohveytqhkbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZnhhbW9iem9odmV5dHFoa2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MDE0OTksImV4cCI6MjA0OTA3NzQ5OX0.q9YZTXeTWEboZ8y4Nx8t58oYqsv7FFR-4aGiILpP3Js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);